import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "../site-shell";
export const metadata: Metadata = { title: "Training" };

export default function Training(){return <><SiteHeader/><main>
  <section className="page-hero shell"><div className="eyebrow">TRAINING / TRAJECTORY SFT</div><h1>Teach the policy from complete runs.</h1><p>The training unit is not a question-answer pair. It is an accepted trajectory containing state, action, observation, evidence decisions and a protocol-valid final report.</p></section>
  <section className="content-section shell"><div className="section-heading"><span className="section-index">01 / DATA FUNNEL</span><h2>Quality before volume.</h2></div><div className="flow">
    <article><b>500</b><h3>Generated</h3><p>Candidate agent trajectories produced under the same runtime contract.</p></article><article><b>479</b><h3>Accepted</h3><p>21 rejected by trajectory-quality and protocol checks.</p></article><article><b>431</b><h3>Train</h3><p>Accepted examples allocated to supervised fine-tuning.</p></article><article><b>48</b><h3>Validation</h3><p>Held back from training for loss and behavior monitoring.</p></article><article><b>2 epochs</b><h3>LoRA SFT</h3><p>Parameter-efficient adaptation of the Qwen3-8B policy.</p></article><article><b>90</b><h3>Held-out test</h3><p>Separate multi-hop questions used for final evaluation.</p></article>
  </div><div className="note">No reinforcement learning is claimed. The current result comes from supervised fine-tuning over filtered agent trajectories.</div></section>
  <section className="content-section shell"><div className="section-heading"><span className="section-index">02 / TRAJECTORY CONTRACT</span><h2>What one example teaches.</h2></div><div className="big-number-grid"><div><strong>STATE</strong><span>Context</span><p>Brief, plan, subtask state, memory, checkpoint and remaining budget.</p></div><div><strong>ACT</strong><span>Decision</span><p>Structured tool choice, query rewrite, assessment or report action.</p></div><div><strong>OBS</strong><span>Feedback</span><p>Tool output, evidence quality signal and contradiction information.</p></div><div><strong>END</strong><span>Protocol</span><p>Supported answer with explicit final evidence identifiers.</p></div></div></section>
  <section className="truth shell"><div><span className="section-index">03 / NEXT TRAINING GATE</span><h2>Scale only after the trace stays clean.</h2></div><div className="truth-copy"><p>The next run should expand accepted high-quality trajectories and training steps while monitoring protocol validity, evidence recall and held-out generalization.</p><p>More steps are useful only if trajectory quality and validation behavior remain stable; checkpoint selection should be evidence-led.</p></div></section>
</main><SiteFooter/></>}
