import type { Metadata } from "next"; import { SiteFooter,SiteHeader } from "../../site-shell";
export const metadata:Metadata={title:"真实系统链路"};
const runtime=[["01","公开网页","DeepTrace-R1 界面","提供已验证轨迹回放，以及真正的实时流式执行模式。"],["02","公开实时网关","/api/live-research · SSE","同源执行规划、BM25 检索、证据门控与状态事件流，模型密钥不进入浏览器。"],["03","Python 参考核心","FastAPI /api/v2/research","完整 Supervisor 支持创建、查看、取消、恢复和检查点恢复。"],["04","后端模型","DeepSeek v4 Flash","负责结构化规划和基于证据的报告生成。"],["05","检索层","固定 BM25 / Brave 适配器","公开实时演示使用 22 条固定 Passage；Brave 已实现，但不宣称完成生产冻结。"],["06","持久化","D1 实时运行 / SQLite 核心","D1 保存公开实时轨迹和配额；SQLite 保存完整 Python ResearchRun 聚合对象。"]];
const training=[["01","本地控制端","代码、数据集和清单在任务下发前完成版本固定。"],["02","SSH 控制通道","通过已配置 SSH alias 传输 Git bundle、启动受控任务并回传产物；主机、用户、密钥与端口不公开。"],["03","远程 GPU 服务器","共享节点可见 8 × RTX 4090；已完成的 SFT 动态选择物理 GPU 4 和 GPU 5。"],["04","训练栈","固定 Qwen3-8B · FSDP2 · BF16 · LoRA rank 16 / alpha 32。"],["05","检查点与 Adapter","step 10 保存模型、优化器、随机数、调度器和数据加载器状态；导出 504 个张量、43,646,976 个 Adapter 参数。"],["06","回传与评估","完成 Adapter 加载生成测试、恢复到 step 11，再进行固定 Base-vs-SFT 90 题独立评估。"]];
export default function Page(){return <><SiteHeader lang="zh"/><main><section className="page-hero shell"><div className="eyebrow">真实系统 / 脱敏基础设施</div><h1>从网页请求到远程 4090 训练。</h1><p>这里展示已经实现并留存证据的项目拓扑。SSH 坐标经过安全脱敏；模型、系统分层、GPU 拓扑和产物流都来自真实项目。</p></section>
<section className="content-section shell"><div className="section-heading"><span className="section-index">01 / 在线服务平面</span><h2>ResearchRun 的真实执行路径。</h2></div><div className="system-rail">{runtime.map(([id,kicker,title,copy])=><article key={id}><b>{id}</b><span>{kicker}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="fact-strip"><span>真实保存运行</span><strong>run-0738372d…</strong><span>后端模型</span><strong>deepseek-v4-flash</strong><span>运行状态</span><strong>检查点 v14</strong><span>验收结果</span><strong>14 / 14</strong></div></section>
<section className="content-section dark-section"><div className="shell"><div className="section-heading"><span className="section-index">02 / 远程训练平面</span><h2>通过 SSH 调度 RTX 4090。</h2></div><div className="system-rail training-rail">{training.map(([id,title,copy])=><article key={id}><b>{id}</b><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="gpu-proof"><div><span>服务器 GPU 清单</span><strong>8 × RTX 4090</strong><small>共享远程节点 · 已保存只读审计</small></div><div><span>本次 SFT 实际设备</span><strong>GPU 4 + GPU 5</strong><small>动态选择 · 训练后恢复至 11 MiB</small></div><div><span>训练步耗时</span><strong>32.09 秒</strong><small>10 个优化器步骤 · 验证损失 1.4181</small></div></div></div></section>
<section className="content-section shell"><div className="section-heading"><span className="section-index">03 / 模型角色</span><h2>一个在线模型、两类调用、一个确定性控制器。</h2></div><div className="role-grid"><article><span>动作策略</span><h3>DeepSeek v4 Flash</h3><p>每个策略步骤只返回一个满足 Schema 的动作：搜索、读页、评估证据或回答。</p></article><article><span>证据写作</span><h3>DeepSeek v4 Flash</h3><p>只接收问题和证据白名单，并以 JSON 返回带引用的最终报告。</p></article><article><span>历史训练实验</span><h3>Qwen3-8B + LoRA</h3><p>已完成的 SFT 结果继续作为项目证据保留，但当前面试演示不部署、也不依赖它。</p></article></div></section>
<section className="truth shell"><div><span className="section-index">04 / 安全与结论边界</span><h2>真实架构，安全披露。</h2></div><div className="truth-copy"><p><strong>公开展示：</strong>远程 GPU 类型和数量、实际选卡、模型身份、训练栈、检查点内容及测量结果。</p><p><strong>绝不公开：</strong>SSH 主机名、IP、用户名、密钥、私有目录和 API 密钥。HTTPS 流式网关必须用本机 Cookie 解锁；解锁后运行次数不限，生产开放网络检索仍不在当前结论范围内。</p></div></section></main><SiteFooter lang="zh"/></>}
